### ISSUE TITLE
Plugin throws error when used with wild card routes

### ISSUE THREAD

**Issue by Fdawgs** [mattbishop/fastify-allow#2]
`fastify-cors` [adds a wildcard (*) OPTIONS route when registered](https://github.com/fastify/fastify-cors/blob/master/index.js#L39). When used with `fastify-allow`, it throws an error:

**Example:**
```js
const fastify = require('fastify')()

fastify.register(require('fastify-allow'))
fastify.register(require('fastify-cors', {origin: true}))

fastify.get('/foo', (req, reply) => {
  reply.send({ hello: 'world' })
})

fastify.post('/foo', (req, reply) => {
  reply.status(201)
})

fastify.listen(3000, (err) => {
  if (err) throw err
  console.log('Server listening at http://localhost:3000')
})
```

Error:
```bash
SyntaxError: Invalid regular expression: /^*/?$/: Nothing to repeat
    at new RegExp (<anonymous>)
    at captureRouteMethod (C:\Repositories\ydh-sider-obfuscation-service\node_modules\fastify-allow\lib\index.js:12:22)
```

**Expected result:**

I would expect the above to not error, and for the `allow` header to be "GET, POST, OPTIONS"

**Comment by mattbishop** [comment]
Thanks for the bug report! I will sort out the wildcard route support.

**Comment by mattbishop** [comment]
Docs on wildcard route (for my reference) https://www.fastify.io/docs/latest/Routes/

**Comment by mattbishop** [comment]
I have a local fix for this, and I have to make a decision about matching wildcards to routes that have no other handlers. If one registers a wildcard like `app.options("*", handler)`, it can catch all requests and always send back 405 for URLs that have no specific matchers. So, `GET /no/handler/here` would return 405.

Or, it can return 404 because the only handler that matches it is the wildcard handler.

Maybe I will make it a configuration with the default being to send 404 when the only matched handler is a wildcard route. Not sure what to call this config. I already have `send405` to turn on 405 sending, so maybe `send405forWildcardRoutes`?

**Comment by Fdawgs** [comment]
Sorry for the slow reply, seems you tackled this well anyway!
Thanks!
